/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    FormItem: typeof import('./src/components/formItem/formItem.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IIcBaselineLogIn: typeof import('~icons/ic/baseline-log-in')['default']
    IMaterialSymbolsClearDayRounded: typeof import('~icons/material-symbols/clear-day-rounded')['default']
    IMaterialSymbolsCodeBlocksOutlineRounded: typeof import('~icons/material-symbols/code-blocks-outline-rounded')['default']
    IMaterialSymbolsExpandMore: typeof import('~icons/material-symbols/expand-more')['default']
    IMaterialSymbolsHelpOutline: typeof import('~icons/material-symbols/help-outline')['default']
    IMaterialSymbolsPartlyCloudyNight: typeof import('~icons/material-symbols/partly-cloudy-night')['default']
    IMaterialSymbolsStarOutlineRounded: typeof import('~icons/material-symbols/star-outline-rounded')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ISvgSpinnersRingResize: typeof import('~icons/svg-spinners/ring-resize')['default']
    Menubar: typeof import('primevue/menubar')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NavBard: typeof import('./src/components/NavBard.vue')['default']
    Password: typeof import('primevue/password')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    ValidateFormItem: typeof import('./src/components/formItem/ValidateFormItem.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
  export interface GlobalDirectives {
    FocusTrap: typeof import('primevue/focustrap')['default']
    Ripple: typeof import('primevue/ripple')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
